services:
  - type: web
    name: vavoo-turkey-iptv
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: VAVOO_DOMAIN
        value: vavoo.to
